### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by invghost** [invghost/Graphite#14]
I think it would be cool to support Android in the future, but it requires some issues to be dealt with before that happens. Notably #11 and #12

**Comment by thatbooisaspy** [comment]
The renderer refactor in d98c494 brings us a step closer to possible android builds!

**Comment by thatbooisaspy** [comment]
A possibly-compatible opengl renderer is added in a199d52

**Comment by invghost** [comment]
Closed because of new plans
